development:
  adapter: mysql2
  database: landmhel
  username: root
  password:
  host: 127.0.0.1
  port: 13306
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: landmhel_test
  username: root
  password:
  host: 127.0.0.1
  port: 13306
  pool: 5
  timeout: 5000

production:
  adapter: 
  username: 
  password:
  database: 
  host: 
  pool: 5
  timeout: 5000